# Generated by Django 2.0.5 on 2018-06-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180618_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenos',
            new_name='ttt',
        ),
    ]
